### ISSUE TITLE
500er on project detail view

### ISSUE THREAD

**Issue by slomo** [liqd/a4-opin#1002]
```
[2017-11-29 19:05:19 +0100] [ERROR] base -- Internal Server Error: /fr/projects/eparticipation-dei-giovani-quale-progetto/
Traceback (most recent call last):
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/rules/compat/access_mixins.py", line 126, in dispatch
    return super(PermissionRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/home/wagtail/wagtail/euth/projects/mixins.py", line 9, in dispatch
    return self._view_by_phase()(request, *args, **kwargs)
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/adhocracy4/projects/mixins.py", line 29, in dispatch
    return super(ProjectMixin, self).dispatch(*args, **kwargs)
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/wagtail/wagtail/lib/python3.4/site-packages/django/views/generic/detail.py", line 116, in get
    context = self.get_context_data(object=self.object)
  File "/home/wagtail/wagtail/euth/flashpoll/views.py", line 48, in get_context_data
    context['poll'] = json.loads(res.text)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```

**Comment by slomo** [comment]
Duplicate of #978
